#!/bin/bash

case $1 in
    login)
        echo "Console sign-in link for root: https://console.aws.amazon.com/console/home?nc2=h_ct&src=header-signin"
        echo "or for IAM user: https://694509815096.signin.aws.amazon.com/console"
        aws configure
        ;;

    init)
        diploma login
        terraform init
        ;;

    plan)
        diploma init
        terraform plan
        ;;

    plan-only)
        terraform plan
        ;;

    apply)
        
        diploma apply-here 
    ;;

    apply-backend)
        -chdir=backend_init
        cd backend_init
        diploma apply-here
        cd ..
        diploma apply-here 
    ;;

    apply-here)
        diploma init
        diploma plan-only
        terraform apply
        ;;

    apply-only)
        terraform apply
        ;;

    destroy)
        diploma init
        terraform destroy
        ;;

    destroy-only)
        terraform destroy
        terraform destroy -chdir=backend_init
        ;;

    unset-creds)
        echo "to unset creds, run:"
        echo "unset AWS_ACCESS_KEY_ID"
        echo "unset AWS_SECRET_ACCESS_KEY"
        ;;

    creds)
        echo "AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY"
        ;;

    check-creds)
        echo $AWS_ACCESS_KEY_ID
        echo $AWS_SECRET_ACCESS_KEY
        ;;

    cleanup)
        rm -r .terraform*
        ;;

    *) echo "Usage: diploma <command> [options]

The available commands for execution are listed below.

Commands:  
 login          'aws configure' with links to login to AWS console
 init           'diploma login' and 'terraform init'
 plan           'diploma init' and 'terraform plan'
 apply          'diploma init' and 'terraform apply'
 destroy        'terraform destroy' with 'diploma login' and 'diploma init'
 unset-creds    instruction how to unset creds
 creds          print AWS access keys names
 check-creds    print AWS access keys values

Options:
 --only     To run dry terraform command without 'diploma login' and 'diploma init'
        "
        #here
        #backend
        #all
        exit 1

esac

