#!/bin/bash

bin='/usr/local/bin'        # cli location
share='/usr/share/diploma' # files location
install="$share/src/install"
msg="$share/src/msg"

case $1 in
#diploma
    install|uninstall)
        $msg nonauthorized $1
        ;;

    update)
        $install force-install
        $msg updated
        ;;

    update-locally)
        ./diploma.sh uninstall
        ./diploma.sh install
        ;;

    version)
        $share/src/msg version
        ;;


    start)
        read -p "Do you want to use aws?" useaws
        read -p "Do you want to use aws?" useaws
        read -p "How to install jenkins?" useaws
    
        ;;

#aws
    login)
        echo "Console sign-in link for root: https://console.aws.amazon.com/console/home?nc2=h_ct&src=header-signin"
        echo "or for IAM user: https://694509815096.signin.aws.amazon.com/console"
        aws configure
        ;;

    unset-creds)
        echo "to unset creds, run:"
        echo "unset AWS_ACCESS_KEY_ID"
        echo "unset AWS_SECRET_ACCESS_KEY"
        ;;

    creds)
        echo "AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY"
        ;;

    check-creds)
        echo $AWS_ACCESS_KEY_ID
        echo $AWS_SECRET_ACCESS_KEY
        ;;

#terraform
    init)
        diploma login
        terraform init
        ;;

    plan)
        diploma init
        terraform plan
        ;;

    plan-only)
        terraform plan
        ;;

    apply)
        
        diploma apply-here 
    ;;

    apply-backend)
        -chdir=backend_init
        cd backend_init
        diploma apply-here
        cd ..
        diploma apply-here 
    ;;

    apply-here)
        diploma init
        diploma plan-only
        terraform apply
        ;;

    apply-only)
        terraform apply
        ;;

    destroy)
        diploma init
        terraform destroy
        ;;

    destroy-only)
        terraform destroy
        terraform destroy -chdir=backend_init
        ;;

    tf-cleanup)
        rm -r .terraform*
        ;;

    help)
        msg help
        ;;

    '') 
        diploma help
        ;;

    *) 
        echo Diploma has no commands named \"$1\".
        echo
        echo To see all of diploma\'s commands, run:
        echo '  diploma help'
        #here
        #backend
        #all
        exit 1

esac

