#!/bin/bash

bin='/usr/local/bin'        # cli location
share='/usr/share/diploma'  # files location
msg='files/src/msg'

case $1 in
    checkinstalled)
        echo whereis `whereis terraform`
        [ $(whereis terraform)='terraform:' &>> err.log ]
        ;;

    configure)
        read -p "" 
        ;;
    *)
        


esac
